### ISSUE TITLE
Create adjusted market feed observation data where liquidity is ballooned/killed

### ISSUE THREAD

**Issue by mesozoic-technology** [overlay-market/overlay-protocol#62]

**Comment by mikeyrf** [comment]
Relevant is this dune query from @deepsp94 

https://dune.xyz/queries/138191

**Comment by mikeyrf** [comment]
Potentially need a check on set price point (would apply to entry and exit then) for current virtual liquidity. In order to determine whether fetched price should be honored.

Relevant are note 2 TWAP manipulation and note 8 market impact slippage manipulation
